# Generated by Django 2.1.1 on 2018-09-21 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cowsayRest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='serverName',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
